name: Release and Publish

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Run in dry-run mode (no actual publishing)'
        required: false
        default: 'false'
        type: boolean

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  # Verify the tag matches the version in Cargo.toml
  verify-version:
    name: Verify Version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Extract version from tag
      id: tag_version
      run: |
        if [[ "${{ github.ref }}" =~ ^refs/tags/v(.*)$ ]]; then
          echo "version=${BASH_REMATCH[1]}" >> $GITHUB_OUTPUT
        else
          echo "version=0.0.0" >> $GITHUB_OUTPUT
        fi

    - name: Extract version from Cargo.toml
      id: cargo_version
      run: |
        VERSION=$(grep -E '^version = ' crates/insign-core/Cargo.toml | head -1 | cut -d'"' -f2)
        echo "version=$VERSION" >> $GITHUB_OUTPUT

    - name: Compare versions
      id: version
      run: |
        TAG_VERSION="${{ steps.tag_version.outputs.version }}"
        CARGO_VERSION="${{ steps.cargo_version.outputs.version }}"
        
        if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
          echo "Manual trigger - using Cargo.toml version: $CARGO_VERSION"
          echo "version=$CARGO_VERSION" >> $GITHUB_OUTPUT
        elif [[ "$TAG_VERSION" == "$CARGO_VERSION" ]]; then
          echo "Version match: $TAG_VERSION"
          echo "version=$TAG_VERSION" >> $GITHUB_OUTPUT
        else
          echo "Version mismatch: tag=$TAG_VERSION, Cargo.toml=$CARGO_VERSION"
          exit 1
        fi

  # Run full test suite before publishing
  test-before-release:
    name: Pre-Release Tests
    runs-on: ubuntu-latest
    needs: [verify-version]
    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: wasm32-unknown-unknown
        components: rustfmt, clippy

    - name: Cache dependencies
      uses: Swatinem/rust-cache@v2

    - name: Check formatting
      run: cargo fmt --all -- --check

    - name: Run clippy
      run: cargo clippy --all-targets --all-features -- -D warnings

    - name: Run all tests
      run: cargo test --all --all-features --verbose

    - name: Install system dependencies for parity test
      run: |
        sudo apt-get update
        sudo apt-get install -y jq python3
        curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
        sudo apt-get install -y nodejs

    - name: Install wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

    - name: Run parity tests
      run: ./tools/scripts/parity-simple.sh

  # Build release artifacts
  build-release-artifacts:
    name: Build Release Artifacts
    needs: [verify-version, test-before-release]
    strategy:
      matrix:
        include:
          # FFI Libraries
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: libinsign_ffi.so
            artifact_type: ffi
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: insign_ffi.dll
            artifact_type: ffi
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: libinsign_ffi.dylib
            artifact_type: ffi
          - os: macos-latest
            target: aarch64-apple-darwin
            artifact_name: libinsign_ffi.dylib
            artifact_type: ffi
          # CLI Binaries
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: insign-cli
            artifact_type: cli
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: insign-cli.exe
            artifact_type: cli
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: insign-cli
            artifact_type: cli
          - os: macos-latest
            target: aarch64-apple-darwin
            artifact_name: insign-cli
            artifact_type: cli
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}

    - name: Cache dependencies
      uses: Swatinem/rust-cache@v2
      with:
        key: release-${{ matrix.target }}-${{ matrix.artifact_type }}

    - name: Build FFI library
      if: matrix.artifact_type == 'ffi'
      run: cargo build --package insign-ffi --release --target ${{ matrix.target }}

    - name: Build CLI binary
      if: matrix.artifact_type == 'cli'
      run: cargo build --package insign --bin insign-cli --release --target ${{ matrix.target }}

    - name: Prepare artifact
      shell: bash
      run: |
        mkdir -p artifacts
        cp target/${{ matrix.target }}/release/${{ matrix.artifact_name }} artifacts/

    - name: Upload release artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact_type }}-${{ matrix.target }}
        path: artifacts/${{ matrix.artifact_name }}

  # Build WASM packages for all targets
  build-wasm-release:
    name: Build WASM Release
    runs-on: ubuntu-latest
    needs: [verify-version, test-before-release]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: wasm32-unknown-unknown

    - name: Cache dependencies
      uses: Swatinem/rust-cache@v2
      with:
        key: wasm-release-all

    - name: Install wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

    - name: Build WASM packages (all targets)
      run: |
        # Use the enhanced build script that creates universal wrappers
        ./build-wasm.sh

    - name: Update package.json files with version and metadata
      run: |
        cd crates/insign-wasm
        for target in nodejs web bundler no-modules; do
          if [[ -d "pkg-${target}" ]]; then
            cd "pkg-${target}"
            node -e "
              const fs = require('fs');
              const pkg = JSON.parse(fs.readFileSync('package.json', 'utf8'));
              pkg.version = '${{ needs.verify-version.outputs.version }}';
              pkg.description = 'Insign: WASM bindings for web/Node.js - A tiny DSL for Minecraft build regions & metadata';
              pkg.repository = { type: 'git', url: 'https://github.com/Schem-at/Insign' };
              pkg.homepage = 'https://github.com/Schem-at/Insign';
              pkg.author = 'Harrison <harrison@schem.at>';
              pkg.license = 'MIT';
              pkg.keywords = ['minecraft', 'schematic', 'dsl', 'wasm', 'regions', 'metadata'];
              pkg.bugs = { url: 'https://github.com/Schem-at/Insign/issues' };
              fs.writeFileSync('package.json', JSON.stringify(pkg, null, 2));
            "
            cd ..
          fi
        done

    - name: Upload WASM artifacts (nodejs)
      uses: actions/upload-artifact@v4
      with:
        name: wasm-nodejs-v${{ needs.verify-version.outputs.version }}
        path: crates/insign-wasm/pkg-nodejs/
        
    - name: Upload WASM artifacts (web)
      uses: actions/upload-artifact@v4
      with:
        name: wasm-web-v${{ needs.verify-version.outputs.version }}
        path: crates/insign-wasm/pkg-web/
        
    - name: Upload WASM artifacts (bundler)
      uses: actions/upload-artifact@v4
      with:
        name: wasm-bundler-v${{ needs.verify-version.outputs.version }}
        path: crates/insign-wasm/pkg-bundler/
        
    - name: Upload WASM artifacts (no-modules)
      uses: actions/upload-artifact@v4
      with:
        name: wasm-no-modules-v${{ needs.verify-version.outputs.version }}
        path: crates/insign-wasm/pkg-no-modules/

  # Publish to crates.io
  publish-crates:
    name: Publish to Crates.io
    runs-on: ubuntu-latest
    needs: [verify-version, test-before-release, build-release-artifacts, build-wasm-release]
    environment: release
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Cache dependencies
      uses: Swatinem/rust-cache@v2

    - name: Publish insign
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
      run: |
        if [[ "${{ inputs.dry_run }}" == "true" ]]; then
          echo "DRY RUN: Would publish insign"
          cargo publish --package insign --dry-run
        else
          cargo publish --package insign
        fi

  # Create GitHub release
  create-github-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [verify-version, publish-crates, build-release-artifacts, build-wasm-release]
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: release-artifacts

    - name: Generate changelog
      id: changelog
      run: |
        if [[ -f CHANGELOG.md ]]; then
          # Extract changelog for this version
          awk '/^## \['"${{ needs.verify-version.outputs.version }}"'\]/, /^## \[/ { 
            if (/^## \['"${{ needs.verify-version.outputs.version }}"'\]/) print; 
            else if (/^## \[/ && !/^## \['"${{ needs.verify-version.outputs.version }}"'\]/) exit; 
            else print 
          }' CHANGELOG.md > release-notes.md
        else
          echo "## What's Changed" > release-notes.md
          echo "" >> release-notes.md
          echo "See commit history for details." >> release-notes.md
        fi

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ needs.verify-version.outputs.version }}
        name: Release v${{ needs.verify-version.outputs.version }}
        body_path: release-notes.md
        files: |
          release-artifacts/ffi-*/libinsign_ffi.so
          release-artifacts/ffi-*/libinsign_ffi.dylib
          release-artifacts/ffi-*/insign_ffi.dll
          release-artifacts/cli-*/insign-cli
          release-artifacts/cli-*/insign-cli.exe
          release-artifacts/wasm-*/insign_bg.wasm
          release-artifacts/wasm-*/insign.js
          release-artifacts/wasm-*/insign.d.ts
        draft: false
        prerelease: ${{ contains(needs.verify-version.outputs.version, 'alpha') || contains(needs.verify-version.outputs.version, 'beta') || contains(needs.verify-version.outputs.version, 'rc') }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Publish WASM packages to npm
  publish-npm:
    name: Publish WASM to npm (${{ matrix.target }})
    runs-on: ubuntu-latest
    needs: [verify-version, build-wasm-release]
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') && !contains(github.ref, 'alpha') && !contains(github.ref, 'beta')
    environment: npm-release
    strategy:
      matrix:
        include:
          - target: nodejs
            package_name: "insign-wasm"
            tag: "latest"
          - target: web
            package_name: "insign-wasm-web"
            tag: "latest"
          - target: bundler
            package_name: "insign-wasm-bundler"
            tag: "latest"
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        registry-url: 'https://registry.npmjs.org'

    - name: Download WASM artifacts
      uses: actions/download-artifact@v4
      with:
        name: wasm-${{ matrix.target }}-v${{ needs.verify-version.outputs.version }}
        path: wasm-${{ matrix.target }}

    - name: Update package name for target-specific packages
      if: matrix.target != 'nodejs'
      run: |
        cd wasm-${{ matrix.target }}
        node -e "
          const fs = require('fs');
          const pkg = JSON.parse(fs.readFileSync('package.json', 'utf8'));
          pkg.name = '${{ matrix.package_name }}';
          pkg.description = pkg.description + ' (${{ matrix.target }} target)';
          fs.writeFileSync('package.json', JSON.stringify(pkg, null, 2));
        "

    - name: Create README for target-specific package
      if: matrix.target != 'nodejs'
      run: |
        cd wasm-${{ matrix.target }}
        cat > README.md << 'EOF'
        # ${{ matrix.package_name }}
        
        This is the **${{ matrix.target }}** target build of [insign-wasm](https://www.npmjs.com/package/insign-wasm).
        
        For the main package with universal support, install:
        ```bash
        npm install insign-wasm
        ```
        
        This target-specific package is optimized for **${{ matrix.target }}** environments.
        
        See the [main insign-wasm documentation](https://github.com/Schem-at/Insign/tree/main/crates/insign-wasm) for usage instructions.
        EOF

    - name: Publish to npm
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
        cd wasm-${{ matrix.target }}
        if [[ "${{ inputs.dry_run }}" == "true" ]]; then
          echo "DRY RUN: Would publish ${{ matrix.package_name }} to npm"
          npm publish --dry-run --tag ${{ matrix.tag }}
        else
          echo "Publishing ${{ matrix.package_name }} to npm with tag ${{ matrix.tag }}"
          npm publish --access public --tag ${{ matrix.tag }}
        fi
